package com.example.demo;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

@Controller
public class UserController {

	// GetMethod

	@GetMapping("/adduser")
	public String greetingForm(Model model) {
		model.addAttribute("user", new User());
		return "adduser";
	}

	// postMethod
	@PostMapping("/adduser")
	public String addUserSubmit(@ModelAttribute Users user) {
		/*User getUser = user;
		addNewUser(getUser.getUsername(), getUser.getPassword());*/
		
		Users n = new Users();
		n.setName(user.getUsername());
		n.setPassword(user.getPassword());
		userRepository.save(n);
		return "result";
	}

	@Autowired // This means to get the bean called userRepository
	// Which is auto-generated by Spring, we will use it to handle the data
	private UsersRepo userRepository;

	@GetMapping(path = "/addTemp") // Map ONLY GET Requests
	public @ResponseBody String addNewUser(@RequestParam String userName, @RequestParam String password) {
		// @ResponseBody means the returned String is the response, not a view name
		// @RequestParam means it is a parameter from the GET or POST request

		Users n = new Users();
		n.setName(userName);
		n.setPassword(password);
		userRepository.save(n);
		return "Saved";
	}

}
